CREATE TABLE IF NOT EXISTS client (
        ID SERIAL PRIMARY KEY,
        NAME VARCHAR(200) CHECK (LENGTH(name) > 3) NOT NULL
    );

CREATE TABLE IF NOT EXISTS planet (
        ID VARCHAR CHECK (id ~ '[A-Z0-9]') PRIMARY KEY,
        NAME VARCHAR(500) CHECK (LENGTH(name) > 1) NOT NULL
    );


CREATE TABLE IF NOT EXISTS ticket (
        ID SERIAL PRIMARY KEY,
        CREATED_AT TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
        CLIENT_ID BIGINT NOT NULL,
        FROM_PLANET_ID VARCHAR NOT NULL,
        TO_PLANET_ID VARCHAR NOT NULL,
        FOREIGN KEY (CLIENT_ID) REFERENCES client (ID),
        FOREIGN KEY (FROM_PLANET_ID) REFERENCES planet (ID),
        FOREIGN KEY (TO_PLANET_ID) REFERENCES planet (ID)
    );